# Generated by Django 3.1.7 on 2021-03-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speciality',
            new_name='Specialty',
        ),
    ]
