# Generated by Django 3.1.7 on 2021-03-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0005_auto_20210331_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='owner',
            new_name='owners',
        ),
    ]
